project_id = "jhnrnhbrtmotblpjollv"

[auth]
[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.email.template]
[auth.email.template.invite]
subject = "You have been invited"
content_path = "./supabase/templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirm your signup"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset your password"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.email_change]
subject = "Confirm email change"
content_path = "./supabase/templates/email_change.html"

[functions.send-auth-email]
verify_jwt = false

[functions.ai-crypto-chat]
verify_jwt = false